### ISSUE TITLE
Header must provide a Content-Length property

### ISSUE THREAD

**Issue by jaxx** [jonathandturner/rls_vscode#15] opened 2016-12-29 07:09 UTC
Hello again!

This problem is somehow related to the problem described by @perlun in https://github.com/jonathandturner/rls_vscode/pull/14. I tried to reproduce the issue. I managed to get the same error and followed these steps:

1. Install Linux Mint 18.1 (RAM: 8GB, HDD: 60GB) and upgrade installed packages and download latest updates
2. Install build-essential and git packages
3. Install rustup 1.0.0 with all toolchains (stable, beta, nightly) and Rust source components for every toolchain
4. Install latest VS Code(1.8.1)
5. Install nodejs v7
6. Clone and build rls (HEAD is on revision `6f46a9f`)
7. Clone rls_vscode and install node modules using `npm install` in project root
8. Make empty executable project in cargo
9. Set RLS_ROOT environment variable and start VS Code
10. Open rls_vscode project and press F5
11. In opened Extension Development Host open empty project and start typing some code
12. VS Code gives an error "Header must provide a Content-Length property" (json looks invalid)

![screenshot at 2016-12-29 08-56-41](https://cloud.githubusercontent.com/assets/723258/21538495/5ad346e8-cda6-11e6-953f-b67170d089f4.png)

**Comment by perlun** [comment] 2016-12-29 17:43
Thanks @jaxx for the detailed steps on reproducing this! I really wonder why this has gone broke all of a sudden.

Can anyone (@nrc, @jonathandturner presumably) who has a _working_ version of this extension list the content of their `node_modules` folder in the `rls_vscode` repo? So we can compare and see if we can bisect it down to which npm module that has changed, causing this.

**Comment by nrc** [comment] 2016-12-30 06:05
Hey, I had a cursory attempt to reproduce this, but could not (still all works for me). From the STR, it looks like you are not running `npm install` which you must do in the directory in which you checkout this repo.

Could you paste the data you are getting from the RLS please (the JSON you suspect to be bad)? From the screenshot it looks to be missing the size field, which would indicate a problem in the RLS, rather than vs code (or any JS modules), but I'm not really sure I'm looking at the right thing.

**Comment by jaxx** [comment] 2016-12-30 06:53
Aah, forgot to add the `npm install` part to the list. Edited. Also I add the picture of the node_modules folder from rls_vscode project. Where I must put the breakpoint to get all the data that RLS is sending?

![screenshot at 2016-12-30 08-52-28](https://cloud.githubusercontent.com/assets/723258/21560830/5aa64158-ce6d-11e6-9819-6a575aad395d.png)

**Comment by PLeVasseur** [comment] 2017-01-03 02:09
I'm seeing the same error message, with the JSON from the RLS as follows:
![screenshot from 2017-01-02 21-01-19](https://cloud.githubusercontent.com/assets/11622119/21598673/b29456c0-d12e-11e6-9208-1de8e3619108.png)

I don't know JSON well, but it does appear to be malformed, so that the Content-Length cannot be parsed out.

Differences in setup from jaxx:
I'm using the nodejs version that came with my Ubuntu distro (v4.2.6).
Installed rust nightly directly from here (https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz) which got me (rustc 1.16.0-nightly (4ecc85beb 2016-12-28)
Got the metadata from (https://static.rust-lang.org/dist/2016-12-28/rust-analysis-nightly-x86_64-unknown-linux-gnu.tar.gz) and put it in the the libs/save-analysis files of the sample_project from rls 
Opened the sample_project that comes with rls

**Comment by jonasbb** [comment] 2017-01-05 15:30
I think I found the cause of the problem. Revision `6f46a9f` contains two `println!` statements in action.rs:66 and build.rs:374. If you comment them out it works. I am not sure why @nrc cannot reproduce it.

The parsing fails due to the missing header. After the first exception the buffer in vscode is no longer synchronized with the message stream and fails to parse the following messages.

**Comment by nrc** [comment] 2017-01-05 21:11
Searching the code, those printlns are no longer there, which would explain why I can no longer repro. Does this bug still happen with master?

**Comment by jonasbb** [comment] 2017-01-05 21:23
I haven't tested it, but I don't think so. I guess he used revision `6f46a9f`because that's what you recommended here https://github.com/jonathandturner/rls/issues/120

**Comment by jaxx** [comment] 2017-01-06 06:10
Yes, @jonasbb is right. I used revision `6f46a9f`. If you say that master is compiling now and this Cargo PR is landed, then I'll try again.

**Comment by nrc** [comment] 2017-01-08 19:54
@jaxx I just landed a commit which uses Cargo from GH rather than a local copy. Everything needed in Cargo itself has landed, so you should be able to build and run from master. (Note though that some jump to def stuff is not working properly right now).

**Comment by jaxx** [comment] 2017-01-09 06:43
Now I'm getting same openssl-sys library error that I described in https://github.com/jonathandturner/rls/issues/120 when I'm trying to compile RLS. Somehow it can't find OpenSSL location. If I check from commandline, OpenSSL is there.

![screenshot at 2017-01-09 08-33-55](https://cloud.githubusercontent.com/assets/723258/21758640/72b5ca08-d646-11e6-8f3c-65c7e68195e0.png)

Stack trace when compiling RLS:

```
1: 0x55c39a3260fc - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
2: 0x55c39a32b55e - std::panicking::default_hook::{{closure}}::h1f61f3c769fffe7a
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
3: 0x55c39a32b164 - std::panicking::default_hook::hd5bda4e453dfb4be
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
4: 0x55c39a32b93b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
5: 0x55c39a29304f - std::panicking::begin_panic::h3bbdbb2a23440035
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
6: 0x55c39a2ad131 - build_script_build::find_openssl_dir::had5f3685f5859ae2
                   at /home/jaxx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.5/build.rs:150
7: 0x55c39a2ac608 - build_script_build::main::{{closure}}::hbd86e5720620dcf7
                   at /home/jaxx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.5/build.rs:19
8: 0x55c39a28cc1c - <core::option::Option<T>>::unwrap_or_else::h31da5bb311ca5018
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:358
9: 0x55c39a2ab709 - build_script_build::main::h0a3886d4bcefcf03
                   at /home/jaxx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.5/build.rs:18
10: 0x55c39a33288a - __rust_maybe_catch_panic
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
11: 0x55c39a32c0a6 - std::rt::lang_start::ha0568cc91d8c5b09
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                   at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
12: 0x55c39a2affd2 - main
13: 0x7ffb2608982f - __libc_start_main
14: 0x55c39a288ab8 - _start
15: 0x0 - <unknown>
```

**Comment by jonasbb** [comment] 2017-01-14 11:47
@jaxx  Did you install the openssl development files? The package name should be `openssl-dev`.

**Comment by jaxx** [comment] 2017-01-14 13:33
@jonasbb Thank you for a hint. I haven't install those packages. The package name is `libssl-dev` and I'll try it out on monday.

**Comment by perlun** [comment] 2017-02-10 21:50
@jaxx I believe the original error here has been resolved. I rebuilt `rls` now and also pulled latest of `rls_vscode` and it works fine for me. The error you reported abuot openssl is really another issue, so I suggest we close this one and you'll reopen a new one re. that if you don't manage to resolve it on your own.

**Closed** 2017-02-11 20:37 UTC
